CREATE TABLE knowledge_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_key CHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    taxonomy_version SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_knowledge_point_key CHECK (knowledge_key ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_knowledge_point_taxonomy_version CHECK (taxonomy_version = 1),
    CONSTRAINT ck_knowledge_point_display_name CHECK (length(btrim(display_name)) > 0)
);

CREATE TABLE learning_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    knowledge_point_id BIGINT NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    event_key CHAR(64) NOT NULL UNIQUE,
    event_version SMALLINT NOT NULL DEFAULT 1,
    signal_value NUMERIC(5, 4),
    signal_weight NUMERIC(5, 4) NOT NULL DEFAULT 0,
    evidence_summary VARCHAR(255),
    reverses_event_id BIGINT UNIQUE,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_learning_event_user
        FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_learning_event_knowledge_point
        FOREIGN KEY (knowledge_point_id) REFERENCES knowledge_point(id),
    CONSTRAINT fk_learning_event_reversal
        FOREIGN KEY (reverses_event_id) REFERENCES learning_event(id),
    CONSTRAINT ck_learning_event_type CHECK (event_type IN (
        'PLAN_DAY_STARTED', 'PLAN_DAY_COMPLETED', 'PLAN_DAY_DELAYED', 'PLAN_DAY_RESET',
        'EXERCISE_ANSWERED', 'EXERCISE_REVIEWED', 'EXERCISE_DELETED',
        'RESOURCE_FEEDBACK_SUBMITTED'
    )),
    CONSTRAINT ck_learning_event_source_type CHECK (source_type IN (
        'PLAN_DAY', 'EXERCISE_RECORD', 'RESOURCE_FEEDBACK'
    )),
    CONSTRAINT ck_learning_event_key CHECK (event_key ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_learning_event_version CHECK (event_version = 1),
    CONSTRAINT ck_learning_event_signal CHECK (signal_value IS NULL OR signal_value BETWEEN 0 AND 1),
    CONSTRAINT ck_learning_event_weight CHECK (signal_weight BETWEEN 0 AND 2),
    CONSTRAINT ck_learning_event_reversal_target CHECK (
        reverses_event_id IS NULL OR reverses_event_id <> id
    )
);

CREATE TABLE mastery_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    knowledge_point_id BIGINT NOT NULL,
    algorithm_version VARCHAR(64) NOT NULL,
    mastery_score NUMERIC(5, 4) NOT NULL,
    confidence NUMERIC(5, 4) NOT NULL,
    effective_weight NUMERIC(12, 4) NOT NULL,
    sample_count INTEGER NOT NULL,
    last_event_id BIGINT NOT NULL,
    calculated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mastery_profile_user
        FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_mastery_profile_knowledge_point
        FOREIGN KEY (knowledge_point_id) REFERENCES knowledge_point(id),
    CONSTRAINT fk_mastery_profile_last_event
        FOREIGN KEY (last_event_id) REFERENCES learning_event(id),
    CONSTRAINT uq_mastery_profile_version
        UNIQUE (user_id, knowledge_point_id, algorithm_version),
    CONSTRAINT ck_mastery_profile_score CHECK (mastery_score BETWEEN 0 AND 1),
    CONSTRAINT ck_mastery_profile_confidence CHECK (confidence BETWEEN 0 AND 0.95),
    CONSTRAINT ck_mastery_profile_effective_weight CHECK (effective_weight > 0),
    CONSTRAINT ck_mastery_profile_sample_count CHECK (sample_count > 0)
);

CREATE INDEX idx_learning_event_user_occurred
    ON learning_event (user_id, occurred_at DESC, id DESC);
CREATE INDEX idx_learning_event_profile_replay
    ON learning_event (user_id, knowledge_point_id, id);
CREATE INDEX idx_learning_event_source
    ON learning_event (source_type, source_id, event_type);
CREATE INDEX idx_learning_event_reversal
    ON learning_event (reverses_event_id)
    WHERE reverses_event_id IS NOT NULL;
CREATE INDEX idx_mastery_profile_user_confidence
    ON mastery_profile (user_id, algorithm_version, confidence DESC, mastery_score ASC);

COMMENT ON TABLE learning_event IS
    'Append-only, privacy-minimized learning evidence used to replay mastery profiles';
COMMENT ON COLUMN learning_event.evidence_summary IS
    'Bounded categorical summary only; never store questions, answers, comments, prompts, tokens or user identity text';
COMMENT ON COLUMN learning_event.reverses_event_id IS
    'Append-only tombstone that excludes one prior event during deterministic replay';
COMMENT ON TABLE mastery_profile IS
    'Versioned, explainable user-knowledge-point projection derived only from learning_event';

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'learnflow_backend') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON knowledge_point, learning_event, mastery_profile TO learnflow_backend;
        GRANT USAGE, SELECT ON SEQUENCE knowledge_point_id_seq, learning_event_id_seq, mastery_profile_id_seq TO learnflow_backend;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'learnflow_agent') THEN
        REVOKE ALL ON knowledge_point, learning_event, mastery_profile FROM learnflow_agent;
        REVOKE ALL ON SEQUENCE knowledge_point_id_seq, learning_event_id_seq, mastery_profile_id_seq FROM learnflow_agent;
    END IF;
END
$$;
