CREATE TABLE adaptive_policy_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    experiment_key VARCHAR(64) NOT NULL,
    variant VARCHAR(16) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    assigned_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adaptive_assignment_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT uq_adaptive_assignment UNIQUE (user_id, experiment_key),
    CONSTRAINT ck_adaptive_assignment_variant CHECK (variant IN ('CONTROL', 'ADAPTIVE')),
    CONSTRAINT ck_adaptive_assignment_experiment CHECK (experiment_key ~ '^[A-Za-z0-9._:-]{1,64}$'),
    CONSTRAINT ck_adaptive_assignment_policy CHECK (policy_version ~ '^[A-Za-z0-9._:-]{1,64}$')
);

CREATE TABLE adaptive_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    experiment_key VARCHAR(64) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    variant VARCHAR(16) NOT NULL,
    surface VARCHAR(16) NOT NULL,
    source_ref VARCHAR(64) NOT NULL,
    context_hash CHAR(64) NOT NULL,
    decision_key CHAR(64) NOT NULL UNIQUE,
    decision_summary VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adaptive_decision_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT ck_adaptive_decision_variant CHECK (variant IN ('CONTROL', 'ADAPTIVE')),
    CONSTRAINT ck_adaptive_decision_surface CHECK (surface IN ('PLAN', 'RESOURCE', 'EXERCISE', 'REPLAN')),
    CONSTRAINT ck_adaptive_decision_context_hash CHECK (context_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_adaptive_decision_key CHECK (decision_key ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_adaptive_decision_user_created
    ON adaptive_decision (user_id, created_at DESC);
CREATE INDEX idx_adaptive_decision_experiment_variant
    ON adaptive_decision (experiment_key, policy_version, variant, surface, created_at DESC);

ALTER TABLE study_plan
    ADD COLUMN adaptation_policy_version VARCHAR(64),
    ADD COLUMN adaptation_variant VARCHAR(16),
    ADD COLUMN adaptation_applied BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN adaptation_reason VARCHAR(64);

ALTER TABLE study_plan
    ADD CONSTRAINT ck_study_plan_adaptation_variant
        CHECK (adaptation_variant IS NULL OR adaptation_variant IN ('CONTROL', 'ADAPTIVE'));

COMMENT ON TABLE adaptive_decision IS
    'Privacy-minimized categorical evidence for replaying adaptive-policy behavior; no content, identity text, answers or prompts';
COMMENT ON COLUMN adaptive_decision.decision_summary IS
    'Bounded categorical output only: target difficulty, review interval, priority and point count';

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'learnflow_backend') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON adaptive_policy_assignment, adaptive_decision TO learnflow_backend;
        GRANT USAGE, SELECT ON SEQUENCE adaptive_policy_assignment_id_seq, adaptive_decision_id_seq TO learnflow_backend;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'learnflow_agent') THEN
        REVOKE ALL ON adaptive_policy_assignment, adaptive_decision FROM learnflow_agent;
        REVOKE ALL ON SEQUENCE adaptive_policy_assignment_id_seq, adaptive_decision_id_seq FROM learnflow_agent;
    END IF;
END
$$;
