CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    email VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    level VARCHAR(20),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_app_user_role CHECK (role IN ('student', 'admin')),
    CONSTRAINT ck_app_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE study_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    goal_text TEXT,
    duration_weeks INTEGER,
    hours_per_day INTEGER,
    level VARCHAR(255),
    title VARCHAR(255),
    start_date DATE,
    end_date DATE,
    status VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_study_plan_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE study_plan_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT,
    day_index INTEGER,
    date DATE,
    title VARCHAR(255),
    tasks_json TEXT,
    status VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_study_plan_day_plan FOREIGN KEY (plan_id) REFERENCES study_plan(id)
);

CREATE TABLE exercise_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_day_id BIGINT,
    user_id BIGINT,
    question TEXT NOT NULL,
    answer_correct TEXT,
    explanation TEXT,
    difficulty VARCHAR(255),
    skill_focus VARCHAR(255),
    answer_user TEXT,
    is_correct BOOLEAN,
    score INTEGER,
    mistake_type VARCHAR(255),
    feedback TEXT,
    next_recommendation TEXT,
    created_at TIMESTAMP(6),
    CONSTRAINT fk_exercise_record_day FOREIGN KEY (plan_day_id) REFERENCES study_plan_day(id),
    CONSTRAINT fk_exercise_record_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE resource_bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_user_id BIGINT,
    uploader_username VARCHAR(100),
    title VARCHAR(300) NOT NULL,
    url TEXT NOT NULL,
    level VARCHAR(255),
    domain VARCHAR(50),
    duration_minutes INTEGER,
    tags TEXT,
    status VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_resource_bank_uploader FOREIGN KEY (uploader_user_id) REFERENCES app_user(id)
);

CREATE TABLE user_resource_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    resource_bank_id BIGINT NOT NULL,
    rating INTEGER,
    comment TEXT,
    is_reported_invalid BOOLEAN,
    created_at TIMESTAMP(6),
    CONSTRAINT fk_resource_feedback_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_resource_feedback_resource FOREIGN KEY (resource_bank_id) REFERENCES resource_bank(id),
    CONSTRAINT ck_resource_feedback_rating CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)
);

CREATE TABLE admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    operator VARCHAR(50),
    target_type VARCHAR(50),
    target_id BIGINT,
    detail TEXT,
    created_at TIMESTAMP(6)
);

CREATE TABLE refresh_token_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    family_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP(6) WITH TIME ZONE,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    replaced_by_token_hash VARCHAR(64),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE agent_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64),
    agent_name VARCHAR(64) NOT NULL,
    request_payload TEXT,
    response_payload TEXT,
    model_name VARCHAR(64),
    duration_ms INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_study_plan_user_created ON study_plan (user_id, created_at DESC);
CREATE INDEX idx_study_plan_day_plan_index ON study_plan_day (plan_id, day_index);
CREATE INDEX idx_exercise_record_user_created ON exercise_record (user_id, created_at DESC);
CREATE INDEX idx_exercise_record_day ON exercise_record (plan_day_id);
CREATE INDEX idx_resource_bank_status_created ON resource_bank (status, created_at DESC);
CREATE INDEX idx_resource_bank_uploader_created ON resource_bank (uploader_user_id, created_at DESC);
CREATE INDEX idx_resource_feedback_user_resource ON user_resource_feedback (user_id, resource_bank_id, created_at DESC);
CREATE INDEX idx_refresh_token_family ON refresh_token_session (family_id);
CREATE INDEX idx_refresh_token_expiry ON refresh_token_session (expires_at);
CREATE INDEX idx_agent_call_log_trace ON agent_call_log (trace_id);
CREATE INDEX idx_agent_call_log_created ON agent_call_log (created_at DESC);
