-- Existing non-empty databases are baselined at version 1, then receive the
-- security/session and Agent-owned tables introduced during production hardening.
CREATE TABLE IF NOT EXISTS refresh_token_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    family_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP(6) WITH TIME ZONE,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    replaced_by_token_hash VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS agent_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64),
    agent_name VARCHAR(64) NOT NULL,
    request_payload TEXT,
    response_payload TEXT,
    model_name VARCHAR(64),
    duration_ms INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_refresh_token_family ON refresh_token_session (family_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_expiry ON refresh_token_session (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_call_log_trace ON agent_call_log (trace_id);
CREATE INDEX IF NOT EXISTS idx_agent_call_log_created ON agent_call_log (created_at DESC);
