CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE INDEX idx_password_reset_user_active
    ON password_reset_token (user_id, expires_at DESC)
    WHERE used_at IS NULL;
CREATE INDEX idx_password_reset_expiry ON password_reset_token (expires_at);
CREATE INDEX idx_admin_audit_log_created ON admin_audit_log (created_at DESC);
CREATE INDEX idx_app_user_lower_email ON app_user (lower(email)) WHERE email IS NOT NULL;
