<template>
  <Teleport to="body">
    <div v-if="user" class="drawer-layer" role="dialog" aria-modal="true" aria-labelledby="user-detail-title">
      <button class="backdrop" type="button" aria-label="关闭用户详情" @click="$emit('close')" /><aside>
    <header><div class="avatar">{{ user.username.slice(0,1).toUpperCase() }}</div><div><span>USER DETAIL</span><h2 id="user-detail-title">{{ user.username }}</h2><p>#{{ user.id }} · {{ user.email || '未填写邮箱' }}</p></div><button type="button" aria-label="关闭" @click="$emit('close')">×</button></header>
    <dl><div><dt>角色</dt><dd>{{ roleLabel(user.role) }}</dd></div><div><dt>状态</dt><dd>{{ statusLabel(user.status) }}</dd></div><div><dt>学习水平</dt><dd>{{ levelLabel(user.level) }}</dd></div><div><dt>注册时间</dt><dd>{{ formatDate(user.createdAt) }}</dd></div></dl>
    <section><div class="section-head"><h3>账号操作</h3><small>所有操作都会写入审计日志</small></div><div class="actions"><button type="button" @click="$emit('action', user, user.role === 'admin' ? 'demote' : 'promote')">{{ user.role === 'admin' ? '改为学习者' : '授权管理员' }}</button><button type="button" :class="{ danger: user.status === 'ACTIVE' }" @click="$emit('action', user, user.status === 'ACTIVE' ? 'disable' : 'enable')">{{ user.status === 'ACTIVE' ? '禁用账号' : '恢复账号' }}</button><button type="button" @click="$emit('action', user, 'reset')">生成临时密码</button></div></section>
    <section><div class="section-head"><h3>最近审计记录</h3><small>{{ audits.length }} 条</small></div><div v-if="audits.length" class="audit-list"><article v-for="audit in audits.slice(0,8)" :key="audit.id"><strong>{{ auditType(audit.type) }}</strong><span>{{ formatDate(audit.createdAt) }} · {{ audit.operator || 'admin' }}</span><p>{{ audit.detail || '没有附加说明' }}</p></article></div><div v-else class="empty">暂无该用户的管理操作记录</div></section>
  </aside>
    </div>
  </Teleport>
</template>
<script setup lang="ts">
import { levelLabel, roleLabel, statusLabel, type AdminAuditRecord, type AdminUserRecord } from './userManagement'
defineProps<{ user: AdminUserRecord | null; audits: AdminAuditRecord[] }>()
defineEmits<{ close: []; action: [user: AdminUserRecord, action: 'promote'|'demote'|'disable'|'enable'|'reset'] }>()
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleString('zh-CN', { hour12:false }) : '未知' }
function auditType(value?: string | null) { return ({ USER_UPDATE:'角色或状态更新', USER_CREATE:'创建用户', USER_RESET_PWD:'重置密码' } as Record<string,string>)[String(value)] || value || '管理操作' }
</script>
<style scoped>
.drawer-layer{position:fixed;inset:0;z-index:4500}.backdrop{position:absolute;inset:0;border:0;background:rgba(7,25,23,.52)}aside{position:absolute;inset:0 0 0 auto;display:flex;width:min(560px,94vw);box-sizing:border-box;flex-direction:column;gap:19px;overflow:auto;padding:23px;background:#f8faf9;box-shadow:-24px 0 70px rgba(0,0,0,.2)}header{display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:12px;align-items:center;padding-bottom:16px;border-bottom:1px solid #dce7e3}.avatar{display:grid;width:48px;height:48px;place-items:center;border-radius:14px;background:#173f38;color:#fff;font-size:18px;font-weight:800}header span{color:#8a5a27;font-size:9px;letter-spacing:.15em}header h2{margin:4px 0;font-size:22px;color:#173d36}header p{margin:0;color:#70807c;font-size:10px}header button{align-self:start;border:0;background:transparent;color:#62736f;font-size:28px;cursor:pointer}dl{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:0}dl>div{padding:12px;border:1px solid #dce6e3;border-radius:11px;background:#fff}dt{color:#788783;font-size:9px;text-transform:uppercase}dd{margin:4px 0 0;color:#29443e;font-size:12px}.section-head{display:flex;justify-content:space-between;align-items:baseline;gap:10px}.section-head h3{margin:0;font-size:14px}.section-head small{color:#7d8c88;font-size:9px}.actions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px;margin-top:10px}.actions button{border:0;border-radius:9px;padding:10px 8px;background:#e5efeb;color:#315c52;font-size:10px;font-weight:750;cursor:pointer}.actions .danger{background:#fff0ec;color:#9d402f}.audit-list{display:grid;gap:7px;margin-top:10px}.audit-list article{padding:11px;border:1px solid #dfe8e5;border-radius:10px;background:#fff}.audit-list strong,.audit-list span{display:block}.audit-list strong{font-size:11px;color:#29443e}.audit-list span{margin-top:3px;color:#788783;font-size:9px}.audit-list p{margin:5px 0 0;color:#5e716c;font-size:10px}.empty{margin-top:10px;padding:20px;text-align:center;border:1px dashed #cfdbd7;border-radius:11px;color:#788783;font-size:10px}@media(max-width:560px){aside{width:100%;padding:17px}.actions{grid-template-columns:1fr}dl{grid-template-columns:1fr}}
</style>
